### ISSUE TITLE
No ::before or ::after?

### ISSUE THREAD

**Issue by richb-hanover** [AdamMarsden/css-cheat-sheet#10]
Is there a reason you don't mention the ::before and ::after selectors? Otherwise a great cheat sheet. Thanks!

**Comment by AdamMarsden** [comment]
@richb-hanover working on some more updates down the line. I think there's a PR with them on. Just haven't had the time to work those in yet!

Coming soon™️

**Comment by richb-hanover** [comment]
Excellent. As we used to say at my old company, "We promise not to fix it if we don't know it's broke" :-) Thanks.
