### ISSUE TITLE
Wrong Attribute Dynamic Value Link on Pretty CSSCS

### ISSUE THREAD

**Issue by brenobarnard** [AdamMarsden/css-cheat-sheet#14]
The "Learn More" link on Attribute Dynamic Value is: 
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters
I think it should be:
[https://developer.mozilla.org/pt-BR/docs/Web/CSS/attr](https://developer.mozilla.org/pt-BR/docs/Web/CSS/attr)

**Comment by AdamMarsden** [comment]
Thanks! Sorted!
