### ISSUE TITLE
Pretty CSSCS - Low readability on mobile

### ISSUE THREAD

**Issue by Ganjalo** [AdamMarsden/css-cheat-sheet#6]
I find the .css-sheet code hard to read on some mobile devices.

The style is fine in desktop dev tools, but lacks contrast when viewed on an actual phone.

Attached is a screenshot from my Galaxy A3 2016 (with the Android status bar) and from Chrome DevTools.

Galaxy A3
![csscs](https://user-images.githubusercontent.com/13832684/35182289-f56dce42-fdd1-11e7-905b-2f8cb656db67.png)

Chrome DevTools
![csscs devtools](https://user-images.githubusercontent.com/13832684/35182330-dee22a00-fdd2-11e7-9078-3b7dda2fd391.png)

PS : Couldn't manage to add a label, help appreciated.

**Comment by AdamMarsden** [comment]
Thanks, @Ganjalo for pointing this out. 

I made sure the text on the site **Passes AA** when building:
![screenshot 2018-01-23 08 51 05](https://user-images.githubusercontent.com/2641173/35266255-950f9e68-001a-11e8-8413-80e2bfabf300.png)
